from __future__ import annotations

from typing import Protocol, runtime_checkable, Optional, Dict, Any, List


@runtime_checkable
class AppointmentAdapter(Protocol):
    """
    Tüm veri kalıcılığı (persistence) katmanları için soyut protokol (interface).
    Tüm CRUD ve slot yönetimi işlemleri bu protokolü implemente etmelidir.
    """

    # ------------------------------------
    # Lifecycle
    # ------------------------------------
    def init(self) -> None: 
        """Veritabanı şemasını başlatır ve gerekirse tabloları oluşturur."""
        ...

    # ------------------------------------
    # Dentist CRUD
    # ------------------------------------
    def create_dentist(self, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_dentist(self, dentist_id: int) -> Optional[Dict[str, Any]]: ...
    def list_dentists(self, is_active: Optional[bool] = True) -> List[Dict[str, Any]]: ...
    def update_dentist(self, dentist_id: int, data: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def delete_dentist(self, dentist_id: int) -> bool: ...

    # ------------------------------------
    # Treatment CRUD
    # ------------------------------------
    def create_treatment(self, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_treatment(self, treatment_id: int) -> Optional[Dict[str, Any]]: ...
    def list_treatments(self, is_active: Optional[bool] = True) -> List[Dict[str, Any]]: ...
    def update_treatment(self, treatment_id: int, data: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def delete_treatment(self, treatment_id: int) -> bool: ...

    # ------------------------------------
    # Appointment CRUD
    # ------------------------------------
    def create_appointment(self, data: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_appointment(self, appointment_id: int) -> Optional[Dict[str, Any]]: ...
    def list_appointments(self, status: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def list_appointments_by_dentist(self, dentist_id: int, status: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def list_appointments_by_date(self, date: str, dentist_id: Optional[int] = None) -> List[Dict[str, Any]]: ...
    def update_appointment(self, appointment_id: int, data: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...
    def delete_appointment(self, appointment_id: int) -> bool: ...

    # ------------------------------------
    # Slot & Approval İşlemleri
    # ------------------------------------
    def get_booked_slots(self, date: str, dentist_id: int) -> List[str]: ...
    def approve_appointment(self, appointment_id: int) -> Optional[Dict[str, Any]]: ...
    def reject_appointment(self, appointment_id: int) -> Optional[Dict[str, Any]]: ...